FROM python:3.9-slim

WORKDIR /app

# Add remaining code to complete the Dockerfile. 
# Docker image should contain both app.py and requirements.py files 
# Install the dependencies in the requirements.tx file using pip
# Run the app.py using cmd command